### ISSUE TITLE
Move ruby implementation in an own branch

### ISSUE THREAD

**Issue by agaida** [hagabaka/sddm-config-editor#19]
To be honest - i guess the preferred implementation will be C++ - unfortunately we have no ruyby guys around

**Comment by hagabaka** [comment]
The Ruby version was an early prototype, so probably not much would be lost by deleting it. However, the `ruby` directory also contains a script which can parse an SDDM example configuration file and generate `data/config-schema.json`, which is basically the C++ application's model, and `cpp/config-strings.qml`, which enables the setting names and descriptions to be localized. This way the application can be semi-automatically updated when SDDM adds/removes settings. The script and supporting files are:
- `ruby/make-config-schema`
- `ruby/parser/example-configuration-file.rb`
- `ruby/parser/ini-file.rb`
- `ruby/parser/setting-conversion.rb`

**Comment by agaida** [comment]
Done - i renamed ruby to maint for now - we should keep the needed files intact
