### ISSUE TITLE
Switch to cmake as build system

### ISSUE THREAD

**Issue by agaida** [hagabaka/sddm-config-editor#20]
just keep LXQt consistent

**Comment by ghost** [comment]
I can help with this, if you want

**Comment by agaida** [comment]
sure, go ahead, thanks

**Comment by yan12125** [comment]
As noticed by stefonarch at #30, translations are not used when cmake is used. The cause appears to be that cmake does not handle `cpp/translations.qrc`, and the fix is not as simple as adding `translations.qrc` besides `qml.qrc` to `CMakeLists.txt`.

**Comment by stefonarch** [comment]
Adding in CMakeLIsts
```
install(
    FILES ${TRANSLATIONS}
    DESTINATION "${CMAKE_INSTALL_DATADIR}/sddm-config-editor/translations"
)
```

installs the *.qm files in place but still doesn't work.

**Comment by YamiYukiSenpai** [comment]
Does this still work with current LXQt?

**Comment by stefonarch** [comment]
Yes.  Be aware that autologin setting has a bug https://github.com/lxqt/sddm-config-editor/issues/50
