### ISSUE TITLE
Add translations to weblate

### ISSUE THREAD

**Issue by agaida** [hagabaka/sddm-config-editor#21]

**Comment by stefonarch** [comment]
https://translate.lxqt-project.org/projects/lxqt-configuration/sddm-config-editor/

This is done, but if I remember well [this](https://github.com/lxqt/sddm-config-editor/blob/master/cpp/translations.qrc) file has to contain all the translations to process while building. Needs testing.

Note to self: the list in this files needs to match the present *.ts files too
https://github.com/lxqt/sddm-config-editor/blob/master/cpp/sddm-config-editor.pro

**Comment by yan12125** [comment]
Webhook is set up, and the weblate component appears to work fine - closing. A remaining issue is that translations do not work with cmake - tracked in #20.
