### ISSUE TITLE
Replace QML with Widgets

### ISSUE THREAD

**Issue by agaida** [hagabaka/sddm-config-editor#23]
I guess that would be fit better with LXQt - it will solve some problems with the current QML implementation too - sddm-config-editor spams a lot of messages to the xsession log - so the question is, if it is worth to fix these things or just to base the UI on  something we know as working well

@tsujan @palinek

**Comment by tsujan** [comment]
We have no QML; do we? `sddm-config-editor` is in QML?

**Comment by tsujan** [comment]
Yes, it is. Tell me when I should run away from LXQt!

**Comment by agaida** [comment]
hihihi - keep calm - we only have to change some ui bits :D

**Comment by agaida** [comment]
erm - the whole ui - we wanted a ui for sddm, we aquired one - and knowed that it wasn't written with LXQt in mind

**Comment by tsujan** [comment]
> keep calm

I try, when, from my superficial viewpoint, I compare this QML combo-box:

![1](https://user-images.githubusercontent.com/981076/47194983-908bb500-d366-11e8-8c59-4ffa0ba29d6a.png)

with this QComboBox:

![2](https://user-images.githubusercontent.com/981076/47195002-9ed9d100-d366-11e8-9eff-e9c90cb0b2d5.png)

Who says GUI is important?

**Comment by tsujan** [comment]
QML is most attractive with a dark gtk2 widget style:

![3](https://user-images.githubusercontent.com/981076/47195467-da759a80-d368-11e8-9c6d-1c1923ab98d2.png)

**Comment by agaida** [comment]
the answer is easy - if not happy with the current state - change it

**Comment by tsujan** [comment]
Today I'm very happy. I don't know about tomorrow.

**Comment by agaida** [comment]
@tsujan - i don't have any plans to release sddm-config-editor pre-mature. With done i mean - no QML, overhauled interface, overhauled functionality if needed. Lesson learned: It is done when it is done.

**Comment by tsujan** [comment]
Converting it to a real Qt/C++ app should be easy. I'll try to do it later but not very soon.

**Comment by agaida** [comment]
take your time
