### ISSUE TITLE
Get rid of QML

### ISSUE THREAD

**Issue by tsujan** [hagabaka/sddm-config-editor#36]
We don't use QML anywhere in LXQt.

I self-assign but will do it only if I find the time. Therefore, if you think you can do it sooner, please tell me!

**Comment by tsujan** [comment]
Oh, my bad! It's like writing a new program. I have no time for that; removed self-assignment.

**Comment by Conan-Kudo** [comment]
SDDM itself uses QML, and maybe it makes sense for this to be part of the SDDM project, since it has no LXQt dependencies?

**Comment by stefonarch** [comment]
This editor is a little lost in nowhere unfortunately: unfixed bugs, GUI issues and therefor it may be archived soon.
Nowhere in LXQt QML is used.
I think focusing efforts on the new application written by @redtide is better: https://github.com/redtide/sddm-conf/
