### ISSUE TITLE
Not All Existing Config File Values Observed

### ISSUE THREAD

**Issue by schijo** [hagabaka/sddm-config-editor#5]
Using latest commit 6009533: Starting config editor shows
a) "Initial Num Lock State" as "on" despite not value set in my config file, i.e. should rather be set to default
b) "Current Theme Name" as "circles" although value set in my config file is different, e.g. "maldives"

When saving the config file those incorrect values are being written to config file. This is incorrect. Values of my config file should be observed.

**Comment by hagabaka** [comment]
@schijo Thanks for reporting this. Could you verify if the new commits fix the issues?

**Comment by schijo** [comment]
Apologies for the delay in response. Was not expecting such prompt reply & fix.
Looking good for me. thx
